### ISSUE TITLE
CloudRail-Examples-“Local-Oauth”-Node.js – Not Working

### ISSUE THREAD

**Issue by NuzumPat** [CloudRail/cloudrail-si-node-sdk#1]
I am having problems running the local-oauth example. Attached is a detailed description of the problems I encounters. 

[cloudRail-Examples-Local-oauth.docx](https://github.com/CloudRail/cloudrail-si-node-sdk/files/422746/cloudRail-Examples-Local-oauth.docx)

Thanks for any assistance,
Pat

**Comment by FlorianWendel** [comment]
Hi there,
thanks for your report.

Could you put a
```
console.log(cs.saveAsString());
```
between the download and getMetadata and check whether the printed JSON string contains a value for "access_token"? If so, we'll know that authentication went well.

The error ("InternalError") you are getting seems to stem from a bug in error reporting on our side, but this part of the code is only reached when the server responded with a status >400 so something else must have gone wrong before.

**Comment by NuzumPat** [comment]
Didn't expect to hear back from anyone so quickly,.. Thanks

The results from the console.log(cs.saveAsString()): [{}]
I don't know what you mean my checking the printed JSON string.

**Comment by FlorianWendel** [comment]
Alright, so the download triggers authentication implicitly which means after that an access token should be present. There isn't one, so it seems like authentication fails.
The part of OAuth to get the authorization code seems to work, judging from your screenshots, so there probably is an issue in the phase where the authorization code is exchanged against an access token.

Could you double check if the client secret is correct?

**Comment by NuzumPat** [comment]
Since I'm running in LocalHost mode, I assumed I did NOT have to add any special Redirect Receiver. Is that correct?

**Comment by FlorianWendel** [comment]
That's correct, for testing on localhost the one provided
```
cloudrail.RedirectReceivers.getLocalAuthenticator(port)
```
should work fine.

**Comment by NuzumPat** [comment]
![ms-reg-portal](https://cloud.githubusercontent.com/assets/21071440/17745283/3ea06e4c-6479-11e6-8959-bd55cffc55d6.jpg)

My Client Secrets look correct.

**Comment by NuzumPat** [comment]
Florian,
Could you hold off until I get back with you. I just went back to another demo that I was using that allowed me to connect to OneDrive, and it is now NOT working. I may have to create a new MS Resitration with new secret code.
Pat

**Comment by FlorianWendel** [comment]
Yes, I believe they recently changed something there.
Our documentation should have up to date instructions:
https://github.com/CloudRail/cloudrail-si-node-sdk/wiki/Services#onedrive

Btw, you should probably not post your application secrets here, this is a public thread after all.

**Comment by NuzumPat** [comment]
I've changed it twice in the last hour,so  that one no longer works. Thanks for the warning!
I'm still having problems getting my other demo to run. I'll let you know when that one is working, and hopefully yours will too!!!!

**Comment by NuzumPat** [comment]
Wendel,
I'm still having problems getting my other example to run. It fails about at the same place yours does. I don't know how your Issues System works, but you want close this, and I can issue a new one if needed.

**Comment by NuzumPat** [comment]
Wendel,
It was my problem. I was doing the MS Application Registration wrong. After I clicked on <Generate New Password>, then I clicked on <Generate New Key Pair>, and used the Private Key as the 3rd parameter in cloudrail.services.OneDrive. I should just be using the Password as the 3rd parameter. 
The Console.log(cs.saveAsString()); displayed a 10 line Access Token.
The cs.download appeared to work, as did the getMetadata, but the cs.upload failed. 
Can you Close this Issue or do I need to Close it?
I'll try and figure out why the cs.upload failed.
Thanks much for your assistance.
Pat

**Comment by NuzumPat** [comment]
<Correcting previous Comment>
It was my problem. I was doing the MS Application Registration wrong. After I clicked on <Generate New Password>, then I clicked on <Generate New Key Pair> , and used the Private Key as the 3rd parameter in cloudrail.services.OneDrive. I should just be using the Password as the 3rd parameter. 
The Console.log(cs.saveAsString()); displayed a 10 line Access Token.
The cs.download appeared to work, as did the getMetadata, but the cs.upload failed. 
Can you Close this Issue or do I need to Close it?
I'll try and figure out why the cs.upload failed.
Thanks much for your assistance.
Pat

**Comment by NuzumPat** [comment]
(Correction to previous 2 Comments,,, using angle braces were not showing up)
It was my problem. I was doing the MS Application Registration wrong. After I clicked on (Generate New Password) , then I clicked on (Generate New Key Pair) , and used the Private Key as the 3rd parameter in cloudrail.services.OneDrive. I should just be using the Password as the 3rd parameter. 
The Console.log(cs.saveAsString()); displayed a 10 line Access Token.
The cs.download appeared to work, as did the getMetadata, but the cs.upload failed. 
Can you Close this Issue or do I need to Close it?
I'll try and figure out why the cs.upload failed.
Thanks much for your assistance.
Pat

**Comment by FlorianWendel** [comment]
Thanks for your feedback,
if you keep having troubles with the upload, feel free to shoot me an email to florian.wendel@cloudrail.com or post to stackoverflow with the CloudRail tag.

**Comment by NuzumPat** [comment]
Thanks!
