### ISSUE TITLE
Forbidden - Make sure that the Google Drive API is enabled.

### ISSUE THREAD

**Issue by NuzumPat** [CloudRail/cloudrail-si-node-sdk#2]
I’ve been using your cloudrail-si in a Node.js, Express website I have been working on. I’ve been using it with OneDrive for a few months now and everything is working. I’m now trying it with Google Drive, and it failed. 
The very first time I ran my application and got the following error in my Debug Console:
Unhandled rejection Error: Forbidden - Make sure that the Google Drive API is enabled

I followed the following directions:
Enable the Drive API
To interact with the Drive API, you need to enable the Drive API service for your app. You can do this in the Google API project for the app.
To enable the Drive API, complete these steps:
1.	Go to the Google API Console.
2.	Select a project.
3.	In the sidebar on the left, expand APIs & auth and select APIs.
4.	In the displayed list of available APIs, click the link for the Drive API and click Enable API.
5.	Within the Drive API page, select the Drive UI Integration tab and begin configuring how your App will integrate with the Drive UI.
All I did was Enable it, and I did not fill in any of the information, because the <Save  Changes> button was never enabled.

Attached are some snippets showing what I have in the Google Drive Portal.

I’m trying to download 194 Files in 35 Folders. What got copied was 14 Files in 19 Folders. A second try got 12 Files, 19 Folders.  Seems like the first dozen work, then when a error occurs, all the rest fail.

Also, the getMetadata, metadata.size, does not give the size of the folder as it does with OneDrive. metadata.size is undefined.
            cs.getMetadata(cs_path, (err, metadata) => {
                if (err) return callback(err);
                console.log("File size is " + metadata.size);
                total_CS_size = metadata.size;  // size in bytes
Thanks for your help,
Pat
![google drive api - 01](https://cloud.githubusercontent.com/assets/21071440/18654026/0d629844-7eac-11e6-82f9-14b81b0ed98c.jpg)
![google drive api - 02](https://cloud.githubusercontent.com/assets/21071440/18654027/0d666f32-7eac-11e6-987b-48ad51703787.jpg)
![google drive api - 03](https://cloud.githubusercontent.com/assets/21071440/18654028/0d692574-7eac-11e6-965d-da344f78d2f4.jpg)
![google drive api - 04](https://cloud.githubusercontent.com/assets/21071440/18654029/0d6b7202-7eac-11e6-8136-fc0632c5ceb3.jpg)
![google drive api - 05](https://cloud.githubusercontent.com/assets/21071440/18654030/0d6bb0dc-7eac-11e6-8843-5b56f1010483.jpg)
![iam-admin-projects](https://cloud.githubusercontent.com/assets/21071440/18654031/0d7107bc-7eac-11e6-8583-254355f69c31.jpg)
[ConsoleLog.txt](https://github.com/CloudRail/cloudrail-si-node-sdk/files/481429/ConsoleLog.txt)

**Comment by FlorianWendel** [comment]
Hi Pat,

I don't know about the directions you are quoting but have you followed the instructions in our documentation (https://github.com/CloudRail/cloudrail-si-node-sdk/wiki/Services#google-drive)? 

To your second question, the Google Drive API does not provide information about folder size, all one can apparently do is sum up the size of the folder's contents. We've considered doing that in our SDK but decided not to since it would dramatically increase how long certain metadata requests take even if the folder size is not used.

**Comment by NuzumPat** [comment]
Hi Florian,

Yes, those are the instructions I followed.

I'll delete it and try again, and track everything I do, and let you know what happens.

It's weird that it allows gets the first 8 files in the root of the directory I'm starting with, but when getting sub-directories, the getChildren starts to fail.

Thanks for your quick reply,

Pat




________________________________

**Comment by NuzumPat** [comment]
After creating a new Google Drive Project and Credentials, the same problems occurred.
Cs.getChildren Failed and cs.download Failed some of the time.

My test is set up with 3 simple cases:
Case 1 - 194 Files, 35 Folders, 97.7 MB - Combination of Case 2 & 3
Case 2 - 182 Files, 30 Folders, 45.4 MB - All .jpg files about 200KB
Case 3 - 4 Files, 3 Folders, 51.5 MB - 2 .pnc and 2 .m4v files. (videos 17,000KB and 34,000 KB)

The max test case I used for OneDrive had over 2,500 files and over 1GB.

Case 3 worked the three times I tried it. Both videos and pictures files copied successfully.

Case 2 had the following results:
Case 2

Files

Folder

MB

G.Drive

182

30

45.4

Trial 1

10 (8 from one folder that had 12)
(2 from a folder that has 8)

14

1.98

Trial 2

0

14

0

Trial 3

2 (in differ folder from Trial 1)

18

.36

Trial 4

2

9

.24

I then changed over to OneDrive and everything was copied successfully.

I have no idea why it is failing most of the time. If you need more information or can give me some guidance on this, it would be appreciated.

I attached snippets from Google Drive Portal, and a DebugLog.

Thanks,
Pat




________________________________

**Comment by NuzumPat** [comment]
Hi Florian,

About that folder size. That is how I determine when the process of copy from CS to FS (FileSystem) has completed. It is all asynchronous using recursive calls into this copy function. The stack may get over 1000 deep at times, but my windows 10 laptop handles it pretty good. At lease for OneDrive.  When I write out a file to the FS, I subtract the length written from the original size of the starting folder (this is where the Google metadat.size doesn't return anything). This count always went to zero after the last file was written.


I've been running many different trails and cases to narrow down there the problem seems to be. Right now, it seems that with a few video files it works most of the time, but not all of the time. The more folders and small jpg files I try to copy, the more failures there are on the GetChrilden and Download fails with that error about enabling that Google Drive API.


Thanks,

Pat



________________________________

**Comment by NuzumPat** [comment]
Here are the results from my testing this afternoon and evening.

9/20/2016 Afternoon & evening

Test Cases:
Case 1 - 194 Files, 35 Folders, 97.7 MB - Combination of Case 2 & 3
Case 2 - 182 Files, 30 Folders, 45.4 MB - All .jpg files about 200KB
Case 3 - 4 Files, 3 Folders, 51.5 MB - 2 .pnc and 2 .m4v files. (videos 17,000KB and 34,000 KB)
Case 4 - 3 Files, 1 Folders, 17.3 MB - 2 files in root(video one of these), one folder with one file.
Case 5 - 6 Files, 2 Folders, 17.6 MB - 2 files in root(video one of these), one folder with one file.
Case 6 - 5 Files, 2 Folders, .332 MB - I deleted video from Case 5.
Case 7 - 9 Files,4 Folders, .652 MB - I deleted video from Case 5.


Case 1

Files

Folder

MB

Comment

G.Drive

194

35

97.7



OneDrive

194

35

97.7



Trial 1-3 OenDrive

194

35

97.7

OneDrive was 100% successful. 3 times

G.Drive

0

2

0

Complete Failure GetChildren & Download

Case 2









G.Drive

33

1

20.8

I made the test much easier. The first file is a 17mb video

Trial 1

4

1

17.5

App restart Video was copied . GetChildren failed on the only folder there

Trial 2

4

1

17.5

App restart. Same as Trial 2

Trial 3

0

1

0

App not restart.

Trial 4

17

1

19.1

App not restart. This was run right after T3 completed. Video copied

Trial 5

1

1

.80

App not restart. This was run right after T4 completed

Trial 6

5

1

.512

App not restart. Video not copied

Trial 7

7

1

.76

App restart. Video not copied

Trial 8

8

1

18.1

App not restarted. Video copied. Things got better if I don't restart app. Sometimes

Case 4

3

1

17.3



Trial 9

3

1

17.3

App restarted. 100% success

Trial 10-13

3

1

17.3

App not restarted. 100% success. 5 successes in a row

Case 5

6

2

17.6



Trial 14-16

6

2

17.6

App not restarted. 100% success.3 successes

Case 6

6

2

.332

Removed video from Case 5

Trial 17

3

2

.178



Trial 18

4

2

.225



Trial 19

3

2

.175

Things got worse when video removed.

Case 7

9

4

.652

Added 2 subfolder under one folder

Trial 20

1

4

.012

This is the first time I got GetChildren errors.2 of them

Trial 21

9

4

.652

App restarted. 100% success

Trial 22

9

4

.652

App not restarted. 100% success

Trial 23

5

4

.332

App not restarted. All were download errors


Summary: It doesn't take much to start getting failures. Does not seem to be a pattern except the fewer folder an files the better chance of success.  I'm hoping that the failures are due to something I didn't do when setting up the Google Drive Portal/API.

Thanks,
Pat



________________________________

**Comment by FlorianWendel** [comment]
Wow, that's a lot of testing.
It's weird that it fails so inconsistently which makes it really hard to find out why.
One thought I had is that most APIs impose some sort of rate limits (e.g. how many requests you can do per second) and I think Google Drive does too, maybe this is what causes the failures.
Could you check if it still fails if you put timeouts between requests? Naturally it will take longer to complete but if you actually hit rate limits before it might just work.

**Comment by NuzumPat** [comment]
Hi Florian,

I'll try what you suggested and let you know.

It sounds correct based on the attachments I attached to this email.

Show rated and errors.

Thanks,

Pat


________________________________

**Comment by NuzumPat** [comment]
I month ago, I did try slowing down the process for OneDrive using setTimeout, but all it did was grow the queue to where I ran out of memory. If you have any suggested it would be appreciated.

I'll Google it and see what I can fine out of slowing down Async operations in Node.js.

-Pat


________________________________

**Comment by NuzumPat** [comment]
Hi Florian,

I tried using the Async package (http://caolan.github.io/async/docs.html#.queue) to slow things down, but had not success.

It doesn't appear I'm using it correctly.

I've attached a zip with the function that causes all the GetChildren and Download errors. One is with the Async module.

I'll keep working on it.

-Pat



________________________________

**Comment by FlorianWendel** [comment]
Hi Pat,

I cannot see the zip file you mentioned, but maybe something like lodash's throttle could do what you need? 

https://lodash.com/docs/4.16.1#throttle

**Comment by NuzumPat** [comment]
It appears this is not a problem with CloudRail s/w, and that I have to throttle my requests to Google Drive in order for it to work. 
Thanks Florian for all you quick and professional assistance,
-Pat
