### ISSUE TITLE
GoogleDrive Redirect url doesn't contain 'state' query 

### ISSUE THREAD

**Issue by William-An** [CloudRail/cloudrail-si-node-sdk#7]
When I am using this sdk, after I authorized my app, the redirect doesn't contain query 'state' but only 'code'. Even if I tried the [official example](https://github.com/CloudRail/cloudrail-si-node-sdk/tree/master/examples/express-oauth-cloudstorage), it still didn't work.

**Comment by PatrickStoklasa** [comment]
Hi William,

Thanks for reporting! The state parameter was indeed missing in GoogleDrive. I added it and it will be part of the next release. I will notify you as soon as it has been released.

**Comment by William-An** [comment]
@PatrickStoklasa Thank you! That relieves me a lot :)

**Comment by PatrickStoklasa** [comment]
Todays release should fix the problem. The SDK is now on version 2.21.0. Let me know if it is working properly for you.

**Comment by William-An** [comment]
Yep, now it works fine, thanks!
