### ISSUE TITLE
Folder or Filename that has an apostrophe (') on Google Drive returns an error on cs.getChildren and cs.download

### ISSUE THREAD

**Issue by NuzumPat** [CloudRail/cloudrail-si-node-sdk#9]
Using latest version 2.21.6. This problem was fixed a long time ago, but creeped back in.
Error Code=undefined
 msg={
 "error": {
  "errors": [
   {
"domain": "global",
    "reason": "invalid",
    "message": "Invalid Value",
    "locationType": "parameter",
    "location": "q"
   }
  ],
  "code": 400,
  "message": "Invalid Value"
  }
}

**Comment by NuzumPat** [comment]
Hi Patrick,,, Great first name!!!
I’ve lost Florian Wendel and can’t find him? Is he still working for your company?
I use your “cloud rail-si-node-sd)”, and have a Community (Free) plan.
I developed a web server that uses your product and am very pleased with it. Just search for “Pat Nuzum” in YouTube and read the Description to get started.
Regards Patrick,
Pat Nuzum
________________________________

**Comment by PatrickStoklasa** [comment]
Hi Pat,
I can only agree, Patrick is indeed a great name ;-) 
That's an interesting product idea. So you are basically setting up the websites for your customers which then pulls in the photos and videos from their cloud storage account?

Florian is not with us anymore, that's correct. If there is anything I can help you with, just let me know!

Best Regards,
Patrick

**Comment by NuzumPat** [comment]
Hi Patrick,

Sorry to hear Florian isn't with your company anymore....

The problem I have when talking to potential customers for my product is me not being able to tell then how much they will be charged by CloudRail.

Is there a way that you can tell me what my monthly charges would have been over the last 6 months if I wasn't getting it for free. I might be able to better explain to my potential customers, what their charges might be.

Thanks,

Pat



________________________________

**Comment by PatrickStoklasa** [comment]
Hi Pat,

I understand. I guess that for the majority of your customers it would be fine to use our free plan. They are just accessing their own pictures and videos so the "branded" authentication should not be an issue either then. If any of your customers need additional support guarantees or things like that they would need a paid plan. 

You can also link to our pricing page https://cloudrail.com/pricing which should have all the information.

**Comment by NuzumPat** [comment]
Thanks Patrick,
I appreciate your information & help,
Patrick
________________________________

**Comment by PatrickStoklasa** [comment]
You're welcome!
